"""initial_all_tables

Revision ID: 3dc38fce7fe7
Revises: 
Create Date: 2026-04-01 08:07:52.166132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dc38fce7fe7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('lessons_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('FAOL', 'NOFAOL', name='coursestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_courses_name', 'courses', ['name'], unique=False)
    op.create_index('ix_courses_status', 'courses', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TEACHER', 'STUDENT', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_rt_token', 'refresh_tokens', ['token'], unique=False)
    op.create_index('ix_rt_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('ERKAK', 'AYOL', name='gender'), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('parent_name', sa.String(length=200), nullable=True),
    sa.Column('parent_phone', sa.String(length=20), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('FAOL', 'KUTISHDA', 'MUZLATILGAN', 'KETGAN', name='studentstatus'), nullable=False),
    sa.Column('debt', sa.Float(), nullable=True),
    sa.Column('paid', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_students_name', 'students', ['name'], unique=False)
    op.create_index('ix_students_phone', 'students', ['phone'], unique=False)
    op.create_index('ix_students_status', 'students', ['status'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('specialty', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('FAOL', 'NOFAOL', name='teacherstatus'), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('experience', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_teachers_name', 'teachers', ['name'], unique=False)
    op.create_index('ix_teachers_status', 'teachers', ['status'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=100), nullable=True),
    sa.Column('schedule', sa.String(length=200), nullable=True),
    sa.Column('time', sa.String(length=50), nullable=True),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('FAOL', 'QABUL_OCHIQ', 'BOSHLANMOQDA', 'YAKUNLANGAN', name='groupstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_groups_course_id', 'groups', ['course_id'], unique=False)
    op.create_index('ix_groups_name', 'groups', ['name'], unique=False)
    op.create_index('ix_groups_status', 'groups', ['status'], unique=False)
    op.create_index('ix_groups_teacher_id', 'groups', ['teacher_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.Enum('CLICK', 'CASH', 'PAYME', 'CARD', name='paymentmethod'), nullable=False),
    sa.Column('status', sa.Enum('MUVAFFAQIYATLI', 'KUTILMOQDA', 'RAD_ETILDI', name='paymentstatus'), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pay_date', 'payments', ['date'], unique=False)
    op.create_index('ix_pay_method', 'payments', ['method'], unique=False)
    op.create_index('ix_pay_status', 'payments', ['status'], unique=False)
    op.create_index('ix_pay_student_id', 'payments', ['student_id'], unique=False)
    op.create_table('salaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('base_amount', sa.Float(), nullable=False),
    sa.Column('bonus', sa.Float(), nullable=True),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sal_month', 'salaries', ['month'], unique=False)
    op.create_index('ix_sal_teacher_id', 'salaries', ['teacher_id'], unique=False)
    op.create_index('ix_sal_unique', 'salaries', ['teacher_id', 'month'], unique=True)
    op.create_table('attendances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', name='attendancestatus'), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_att_date', 'attendances', ['date'], unique=False)
    op.create_index('ix_att_group_id', 'attendances', ['group_id'], unique=False)
    op.create_index('ix_att_student_id', 'attendances', ['student_id'], unique=False)
    op.create_index('ix_att_unique', 'attendances', ['student_id', 'group_id', 'date'], unique=True)
    op.create_table('student_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sg_group_id', 'student_groups', ['group_id'], unique=False)
    op.create_index('ix_sg_student_id', 'student_groups', ['student_id'], unique=False)
    op.create_index('ix_sg_unique', 'student_groups', ['student_id', 'group_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sg_unique', table_name='student_groups')
    op.drop_index('ix_sg_student_id', table_name='student_groups')
    op.drop_index('ix_sg_group_id', table_name='student_groups')
    op.drop_table('student_groups')
    op.drop_index('ix_att_unique', table_name='attendances')
    op.drop_index('ix_att_student_id', table_name='attendances')
    op.drop_index('ix_att_group_id', table_name='attendances')
    op.drop_index('ix_att_date', table_name='attendances')
    op.drop_table('attendances')
    op.drop_index('ix_sal_unique', table_name='salaries')
    op.drop_index('ix_sal_teacher_id', table_name='salaries')
    op.drop_index('ix_sal_month', table_name='salaries')
    op.drop_table('salaries')
    op.drop_index('ix_pay_student_id', table_name='payments')
    op.drop_index('ix_pay_status', table_name='payments')
    op.drop_index('ix_pay_method', table_name='payments')
    op.drop_index('ix_pay_date', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_groups_teacher_id', table_name='groups')
    op.drop_index('ix_groups_status', table_name='groups')
    op.drop_index('ix_groups_name', table_name='groups')
    op.drop_index('ix_groups_course_id', table_name='groups')
    op.drop_table('groups')
    op.drop_index('ix_teachers_status', table_name='teachers')
    op.drop_index('ix_teachers_name', table_name='teachers')
    op.drop_table('teachers')
    op.drop_index('ix_students_status', table_name='students')
    op.drop_index('ix_students_phone', table_name='students')
    op.drop_index('ix_students_name', table_name='students')
    op.drop_table('students')
    op.drop_index('ix_rt_user_id', table_name='refresh_tokens')
    op.drop_index('ix_rt_token', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_courses_status', table_name='courses')
    op.drop_index('ix_courses_name', table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
